-- MySQL Script generated by MySQL Workbench
-- Tue Apr 15 15:49:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zuehlkePraktikum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zuehlkePraktikum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zuehlkePraktikum` DEFAULT CHARACTER SET utf8 ;
USE `zuehlkePraktikum` ;

-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`weapon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `damagePerHit` INT NOT NULL DEFAULT 0,
  `attackSpeed` INT NOT NULL DEFAULT 0,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`headgear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`headgear` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `defense` INT NOT NULL DEFAULT 0,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`consumable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`consumable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`race` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `health` INT NOT NULL DEFAULT 100,
  `magicka` INT NOT NULL DEFAULT 100,
  `stamina` INT NOT NULL DEFAULT 100,
  `skill` INT NOT NULL DEFAULT 0,
  `imageMale` MEDIUMBLOB NOT NULL,
  `imageFemale` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`chest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`chest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `defense` INT NOT NULL DEFAULT 0,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`gloves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`gloves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `defense` INT NOT NULL DEFAULT 0,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`legs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`legs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `defense` INT NOT NULL DEFAULT 0,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`characterConfiguration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`characterConfiguration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `userId` INT NOT NULL,
  `raceId` INT NOT NULL,
  `headgearId` INT NOT NULL,
  `chestId` INT NOT NULL,
  `glovesId` INT NOT NULL,
  `legsId` INT NOT NULL,
  `weaponId` INT NOT NULL,
  `consumableId` INT NOT NULL,
  `sex` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_character_user_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_character_race1_idx` (`raceId` ASC) VISIBLE,
  INDEX `fk_character_weapon1_idx` (`weaponId` ASC) VISIBLE,
  INDEX `fk_character_consumable1_idx` (`consumableId` ASC) VISIBLE,
  INDEX `fk_characterConfiguration_headgear1_idx` (`headgearId` ASC) VISIBLE,
  INDEX `fk_characterConfiguration_chest1_idx` (`chestId` ASC) VISIBLE,
  INDEX `fk_characterConfiguration_gloves1_idx` (`glovesId` ASC) VISIBLE,
  INDEX `fk_characterConfiguration_legs1_idx` (`legsId` ASC) VISIBLE,
  CONSTRAINT `fk_character_user`
    FOREIGN KEY (`userId`)
    REFERENCES `zuehlkePraktikum`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_race1`
    FOREIGN KEY (`raceId`)
    REFERENCES `zuehlkePraktikum`.`race` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_weapon1`
    FOREIGN KEY (`weaponId`)
    REFERENCES `zuehlkePraktikum`.`weapon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_consumable1`
    FOREIGN KEY (`consumableId`)
    REFERENCES `zuehlkePraktikum`.`consumable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characterConfiguration_headgear1`
    FOREIGN KEY (`headgearId`)
    REFERENCES `zuehlkePraktikum`.`headgear` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characterConfiguration_chest1`
    FOREIGN KEY (`chestId`)
    REFERENCES `zuehlkePraktikum`.`chest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characterConfiguration_gloves1`
    FOREIGN KEY (`glovesId`)
    REFERENCES `zuehlkePraktikum`.`gloves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characterConfiguration_legs1`
    FOREIGN KEY (`legsId`)
    REFERENCES `zuehlkePraktikum`.`legs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
