-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 16:52:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zuehlkePraktikum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zuehlkePraktikum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zuehlkePraktikum` DEFAULT CHARACTER SET utf8 ;
USE `zuehlkePraktikum` ;

-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zuehlkePraktikum`.`user` ;

CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` BIGINT NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`weapon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zuehlkePraktikum`.`weapon` ;

CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`weapon` (
  `weaponId` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `damagePerHit` INT NULL,
  `attackSpeed` INT NULL,
  PRIMARY KEY (`weaponId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`clothing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zuehlkePraktikum`.`clothing` ;

CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`clothing` (
  `clothingID` INT NOT NULL,
  `defense` INT NULL,
  `clothingType` INT NULL,
  PRIMARY KEY (`clothingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`consumable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zuehlkePraktikum`.`consumable` ;

CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`consumable` (
  `consumableId` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`consumableId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zuehlkePraktikum`.`race` ;

CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`race` (
  `raceId` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `health` INT NOT NULL,
  `magicka` INT NOT NULL,
  `stamina` INT NOT NULL,
  `skill` INT NOT NULL,
  PRIMARY KEY (`raceId`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zuehlkePraktikum`.`character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zuehlkePraktikum`.`character` ;

CREATE TABLE IF NOT EXISTS `zuehlkePraktikum`.`character` (
  `characterId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `user_userId` INT NOT NULL,
  `race_raceId` INT NOT NULL,
  `clothing_headgearId` INT NOT NULL,
  `clothing_chestId` INT NOT NULL,
  `clothing_glovesId` INT NOT NULL,
  `clothing_legsId` INT NOT NULL,
  `weapon_weaponId` INT NOT NULL,
  `consumable_consumableId` INT NOT NULL,
  PRIMARY KEY (`characterId`),
  INDEX `fk_character_user_idx` (`user_userId` ASC) VISIBLE,
  INDEX `fk_character_race1_idx` (`race_raceId` ASC) VISIBLE,
  INDEX `fk_character_clothing1_idx` (`clothing_headgearId` ASC) VISIBLE,
  INDEX `fk_character_clothing2_idx` (`clothing_chestId` ASC) VISIBLE,
  INDEX `fk_character_clothing3_idx` (`clothing_glovesId` ASC) VISIBLE,
  INDEX `fk_character_clothing4_idx` (`clothing_legsId` ASC) VISIBLE,
  INDEX `fk_character_weapon1_idx` (`weapon_weaponId` ASC) VISIBLE,
  INDEX `fk_character_consumable1_idx` (`consumable_consumableId` ASC) VISIBLE,
  CONSTRAINT `fk_character_user`
    FOREIGN KEY (`user_userId`)
    REFERENCES `zuehlkePraktikum`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_race1`
    FOREIGN KEY (`race_raceId`)
    REFERENCES `zuehlkePraktikum`.`race` (`raceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_clothing1`
    FOREIGN KEY (`clothing_headgearId`)
    REFERENCES `zuehlkePraktikum`.`clothing` (`clothingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_clothing2`
    FOREIGN KEY (`clothing_chestId`)
    REFERENCES `zuehlkePraktikum`.`clothing` (`clothingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_clothing3`
    FOREIGN KEY (`clothing_glovesId`)
    REFERENCES `zuehlkePraktikum`.`clothing` (`clothingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_clothing4`
    FOREIGN KEY (`clothing_legsId`)
    REFERENCES `zuehlkePraktikum`.`clothing` (`clothingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_weapon1`
    FOREIGN KEY (`weapon_weaponId`)
    REFERENCES `zuehlkePraktikum`.`weapon` (`weaponId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_consumable1`
    FOREIGN KEY (`consumable_consumableId`)
    REFERENCES `zuehlkePraktikum`.`consumable` (`consumableId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
